stages:
- name: Build
  steps:
  - runScriptConfig:
      image: demo.harbor.cnrancher.com/library/busybox:1.28
      shellScript: |-
        echo "Start building phase"
        echo $PWD

        # sed -i "s/V2/2.0.${CICD_EXECUTION_SEQUENCE}/" src/index.html
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demo.harbor.cnrancher.com/rancher/pipeline-html:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: demo.harbor.cnrancher.com
    env:
      PLUGIN_INSECURE: "true"
- name: Catalog
  steps:
  - publishCatalogConfig:
      path: ./charts
      catalogTemplate: html
      version: 1.0.${CICD_EXECUTION_SEQUENCE}
      gitUrl: https://github.com/JackieYou/pipeline-charts.git
      gitBranch: master
      gitAuthor: JackieYou
      gitEmail: jiqing@rancher.com
    envFrom:
    - sourceName: github
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: github
      sourceKey: PASSWORD
      targetKey: PASSWORD
timeout: 60
notification: {}
