apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pipeline-demo
    from: pipeline
  name: pipeline-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-demo
  template:
    metadata:
      labels:
        app: pipeline-demo
    spec:
      containers:
      - image: harbor.youjiqing.club/rancher/nginx:${CICD_EXECUTION_SEQUENCE}
        imagePullPolicy: Always
        name: demo
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
