app:
  name: pipeline-html

deployment:
  replicas: "1"
  pullpolicy: IfNotPresent
  image: demo.harbor.cnrancher.com/rancher/pipeline-html:${CICD_EXECUTION_SEQUENCE}

service:
  type: ClusterIP

ingress:
  host: pipeline.youjiqing.xyz
